trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubPATGroup
- name: buildConfiguration
  value: 'Release'

steps:
- script: |
    cargo install wasm-pack
    cargo install cargo-make
  displayName: install tools

- script: cargo make fixrel
  displayName: Publish App

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    contents: |
      static/*
      LICENSE
    targetFolder: $(Build.ArtifactStagingDirectory)/wwwroot

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/wwwroot
    artifactName: 'Dist'

- script: |
    git config --global user.name "$NAME"
    git config --global user.email "$EMAIL"
    cd $(Build.ArtifactStagingDirectory)/wwwroot
    git init
    git checkout -b master
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push -f https://$PAT@github.com/Berrysoft/Berrysoft.github.io.git master
  displayName: 'Publish to GitHub Pages'
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)
