trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubPATGroup

steps:
- script: |
    cargo install trunk
    rustup target add wasm32-unknown-unknown
  displayName: Install tools

- script: trunk build --release
  displayName: Build app

- task: CopyFiles@2
  displayName: Copy files
  inputs:
    contents: |
      dist/**
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/dist
    artifactName: 'Dist'

- script: |
    git config --global user.name "$NAME"
    git config --global user.email "$EMAIL"
    cd $(Build.ArtifactStagingDirectory)/dist
    git init
    git checkout -b master
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push -f https://$PAT@github.com/Berrysoft/Berrysoft.github.io.git master
  displayName: 'Publish to GitHub Pages'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)
