trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubPATGroup

steps:
- script: |
    cargo install wasm-pack
    cargo install cargo-make
  displayName: Install tools

- script: cargo make fixrel
  displayName: Build app

- task: CopyFiles@2
  displayName: Copy files
  inputs:
    contents: |
      static/**
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/static
    artifactName: 'Dist'

- script: |
    git config --global user.name "$NAME"
    git config --global user.email "$EMAIL"
    cd $(Build.ArtifactStagingDirectory)/static
    git init
    git checkout -b master
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push -f https://$PAT@github.com/Berrysoft/Berrysoft.github.io.git master
  displayName: 'Publish to GitHub Pages'
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)
