trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubPATGroup
- name: buildConfiguration
  value: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install Latest .NET Core 3.0 SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.100-rc1-014190'

- task: DotNetCoreCLI@2
  displayName: Build App
  inputs:
    command: build
    projects: Berrysoft.Pages/Berrysoft.Pages.csproj
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Publish App
  inputs:
    command: publish
    projects: Berrysoft.Pages/Berrysoft.Pages.csproj
    # Important: If you zip the publish, the GitHub Pages script will need to unzip it first
    zipAfterPublish: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: Copy License
  inputs:
    contents: 'LICENSE'
    targetFolder: $(Build.ArtifactStagingDirectory)/Berrysoft.Pages/Berrysoft.Pages/dist

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/Berrysoft.Pages
    artifactName: 'Dist'

- script: |
    git config --global user.name "$NAME"
    git config --global user.email "$EMAIL"
    cd $(Build.ArtifactStagingDirectory)/Berrysoft.Pages/Berrysoft.Pages/dist
    git init
    git checkout -b master
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push -f https://$PAT@github.com/Berrysoft/Berrysoft.github.io.git master
  displayName: 'Publish to GitHub Pages'
  env:
    PAT: $(GitHubPAT)
    NAME: $(GitHubName)
    EMAIL: $(GitHubEmail)
