[package]
name = "pages"
version = "0.1.0"
edition = "2018"
description = "Berrysoft's personal site."
repository = "https://github.com/Berrysoft/Berrysoft.github.io.git"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "blog"
required-features = ["blog"]

[dependencies]
wasm-bindgen = "0.2"
log = "0.4"
wasm-logger = "0.2"
yew = "0.18"
yew-router = "0.15"
anyhow = "1.0"
wee_alloc = "0.4"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
rss = "2.0"
pulldown-cmark = { version = "0.9", default-features = false }
url = "2.2"

structopt = { version = "0.3", optional = true }

[features]
default = []
blog = ["structopt"]

[profile.release]
lto = true
