[package]
name = "pages"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "blog"
required-features = ["blog"]

[dependencies]
web-sys = { version = "0.3", features = ["DomParser", "Document", "SupportedType", "HtmlCollection"] }
wasm-bindgen = "0.2"
yew = "0.17"
yew-router = "0.14"
anyhow = "1.0"
http = "0.2"
wee_alloc = "0.4"
console_error_panic_hook = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
lazy_static = "1.4"
rss = "1.10"
pulldown-cmark = { version = "0.8", default-features = false }

structopt = { version = "0.3", optional = true }

[features]
default = []
blog = ["structopt"]

[profile.release]
lto = true
