[tasks.buildwasm]
script = [
    "wasm-pack build --dev --target web --no-typescript --out-name wasm --out-dir ./static",
    "git restore ./static/.gitignore"
]

[tasks.serve]
dependencies = ["buildwasm"]
command = "simple-http-server"
args = ["-i", "./static/", "-p", "3000", "--nocache", "--try-file", "./static/404.html"]
